# Generated by Django 3.2.7 on 2021-09-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
